sonar.projectKey=zenprocess_pawbench
sonar.organization=zenprocess
sonar.projectName=PawBench

sonar.sources=src/pawbench
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml

sonar.python.version=3.10,3.11,3.12
